config/routes.rb
Nimatel::Application.routes.draw do

  resources :retailers

  resources :countries

  resources :cards, :constraints => {:subdomain => 'admin'}

  scope :controller => :home do
    match "rates" => :rates, :as => :rates
    match "about" => :about, :as => :about
    get "contact" => :contact_get, :as => :contact
    post "contact" => :contact_post, :as => :contact_post
    put "contact" => :contact_post, :as => :contact_post
    match "access" => :access, :as => :accesss
    match "terms" => :terms, :as => :terms
    match "how" => :how, :as => :how
  end

  scope :controller => :admin, :constraints => {:subdomain => 'admin' } do
    match "/" => :index
    match "logs" => :logs, :as => :logs
  end

  get "login" => "sessions#new", :as => :login
  post "login" => "sessions#destroy", :as => :login
  match "logout" => "sessions#destroy", :as => :logout
  get "register" => "users#new", :as => :register
  post "register" => "users#create", :as => :register

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation, :cim_profile_id, :default_payment_profile_id

	has_many :cards
	has_many :phone_numbers
	has_many :payment_profiles
	has_one :renewal_plan
	has_many :transactions
	has_secure_password
	validates_presence_of :password, :on => :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, :notice => "Signed up!"
		else
			render "new"
		end
	end
end

app/views/users/new.html.erb
<%= form_tag register_url(protocol: "https") do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email %>
	</div>
	<div class="field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
	</div>
	<div class="field">
		<%= label_tag :password_confirmation %>
		<%= password_field_tag :password_confirmation %>
	</div>
	<div class="actions"><%= submit_tag "Register"  %></div>
<% end %>