config/routes.rb
Nimatel::Application.routes.draw do

  resources :retailers

  resources :countries

  resources :cards, :constraints => {:subdomain => 'admin'}

  scope :controller => :home do
    match "rates" => :rates, :as => :rates
    match "about" => :about, :as => :about
    get "contact" => :contact_get, :as => :contact
    post "contact" => :contact_post, :as => :contact_post
    put "contact" => :contact_post, :as => :contact_post
    match "access" => :access, :as => :accesss
    match "terms" => :terms, :as => :terms
    match "how" => :how, :as => :how
  end

  scope :controller => :admin, :constraints => {:subdomain => 'admin' } do
    match "/" => :index
    match "logs" => :logs, :as => :logs
  end

  get "login" => "sessions#new", :as => :login
  post "login" => "sessions#destroy", :as => :login
  match "logout" => "sessions#destroy", :as => :logout
  get "register" => "users#new", :as => :register
  post "register" => "users#create", :as => :register

  root :to => 'home#index'

end

app/models/retailer.rb
class Retailer < ActiveRecord::Base
  attr_accessible :address, :city, :contact, :contact_title, :country, :email, :fax_number, :gender, :has_calling_card, :industry, :name, :num_employees, :phone_number, :sales, :sic, :sic_description, :state, :website, :zip
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  # GET /retailers
  # GET /retailers.json
  def index
    @retailers = Retailer.all.page(params[:page]).per(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @retailers }
    end
  end

  # GET /retailers/1
  # GET /retailers/1.json
  def show
    @retailer = Retailer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @retailer }
    end
  end

  # GET /retailers/new
  # GET /retailers/new.json
  def new
    @retailer = Retailer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @retailer }
    end
  end

  # GET /retailers/1/edit
  def edit
    @retailer = Retailer.find(params[:id])
  end

  # POST /retailers
  # POST /retailers.json
  def create
    @retailer = Retailer.new(params[:retailer])

    respond_to do |format|
      if @retailer.save
        format.html { redirect_to @retailer, notice: 'Retailer was successfully created.' }
        format.json { render json: @retailer, status: :created, location: @retailer }
      else
        format.html { render action: "new" }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /retailers/1
  # PUT /retailers/1.json
  def update
    @retailer = Retailer.find(params[:id])

    respond_to do |format|
      if @retailer.update_attributes(params[:retailer])
        format.html { redirect_to @retailer, notice: 'Retailer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retailers/1
  # DELETE /retailers/1.json
  def destroy
    @retailer = Retailer.find(params[:id])
    @retailer.destroy

    respond_to do |format|
      format.html { redirect_to retailers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/_form.html.erb
<%= form_for(@retailer) do |f| %>
  <% if @retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <ul>
      <% @retailer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :fax_number %><br />
    <%= f.text_field :fax_number %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :contact_title %><br />
    <%= f.text_field :contact_title %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :num_employees %><br />
    <%= f.number_field :num_employees %>
  </div>
  <div class="field">
    <%= f.label :sales %><br />
    <%= f.text_field :sales %>
  </div>
  <div class="field">
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :sic %><br />
    <%= f.text_field :sic %>
  </div>
  <div class="field">
    <%= f.label :sic_description %><br />
    <%= f.text_field :sic_description %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :has_calling_card %><br />
    <%= f.check_box :has_calling_card %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/retailers/edit.html.erb
<h1>Editing retailer</h1>

<%= render 'form' %>

<%= link_to 'Show', @retailer %> |
<%= link_to 'Back', retailers_path %>

app/views/retailers/index.html.erb
<%= paginate @retailers %>

<h1>Listing retailers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Country</th>
    <th>Gender</th>
    <th>Phone number</th>
    <th>Fax number</th>
    <th>Contact</th>
    <th>Contact title</th>
    <th>Website</th>
    <th>Num employees</th>
    <th>Sales</th>
    <th>Industry</th>
    <th>Sic</th>
    <th>Sic description</th>
    <th>Email</th>
    <th>Has calling card</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @retailers.each do |retailer| %>
  <tr>
    <td><%= retailer.name %></td>
    <td><%= retailer.address %></td>
    <td><%= retailer.city %></td>
    <td><%= retailer.state %></td>
    <td><%= retailer.zip %></td>
    <td><%= retailer.country %></td>
    <td><%= retailer.gender %></td>
    <td><%= retailer.phone_number %></td>
    <td><%= retailer.fax_number %></td>
    <td><%= retailer.contact %></td>
    <td><%= retailer.contact_title %></td>
    <td><%= retailer.website %></td>
    <td><%= retailer.num_employees %></td>
    <td><%= retailer.sales %></td>
    <td><%= retailer.industry %></td>
    <td><%= retailer.sic %></td>
    <td><%= retailer.sic_description %></td>
    <td><%= retailer.email %></td>
    <td><%= retailer.has_calling_card %></td>
    <td><%= link_to 'Show', retailer %></td>
    <td><%= link_to 'Edit', edit_retailer_path(retailer) %></td>
    <td><%= link_to 'Destroy', retailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Retailer', new_retailer_path %>

app/views/retailers/new.html.erb
<h1>New retailer</h1>

<%= render 'form' %>

<%= link_to 'Back', retailers_path %>

app/views/retailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @retailer.name %>
</p>

<p>
  <b>Address:</b>
  <%= @retailer.address %>
</p>

<p>
  <b>City:</b>
  <%= @retailer.city %>
</p>

<p>
  <b>State:</b>
  <%= @retailer.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @retailer.zip %>
</p>

<p>
  <b>Country:</b>
  <%= @retailer.country %>
</p>

<p>
  <b>Gender:</b>
  <%= @retailer.gender %>
</p>

<p>
  <b>Phone number:</b>
  <%= @retailer.phone_number %>
</p>

<p>
  <b>Fax number:</b>
  <%= @retailer.fax_number %>
</p>

<p>
  <b>Contact:</b>
  <%= @retailer.contact %>
</p>

<p>
  <b>Contact title:</b>
  <%= @retailer.contact_title %>
</p>

<p>
  <b>Website:</b>
  <%= @retailer.website %>
</p>

<p>
  <b>Num employees:</b>
  <%= @retailer.num_employees %>
</p>

<p>
  <b>Sales:</b>
  <%= @retailer.sales %>
</p>

<p>
  <b>Industry:</b>
  <%= @retailer.industry %>
</p>

<p>
  <b>Sic:</b>
  <%= @retailer.sic %>
</p>

<p>
  <b>Sic description:</b>
  <%= @retailer.sic_description %>
</p>

<p>
  <b>Email:</b>
  <%= @retailer.email %>
</p>

<p>
  <b>Has calling card:</b>
  <%= @retailer.has_calling_card %>
</p>


<%= link_to 'Edit', edit_retailer_path(@retailer) %> |
<%= link_to 'Back', retailers_path %>